document.getElementById('show-add-money-form').addEventListener('click',()=>{
    showSectionById('show-add-money')
})
document.getElementById('cashout-btn').addEventListener('click',()=>{
    showSectionById('show-cashout')
})
document.getElementById('transaction-btn').addEventListener('click',()=>{
    showSectionById('show-transaction')
})
document.getElementById('history-btn').addEventListener('click',()=>{
    showSectionById('show-history')
})